# 🚀 Backend Developer Journey — Project 1 (URL Shortener API)

# Day 53 — API Schemas (Pydantic)

# Right now our project looks like this: Client -> FastAPI -> ??? -> Model -> Database
# The ??? is the missing piece. If we build the repository first, we'll have no way to validate incoming data.
# So today we'll build the Schema Layer. No endpoints yet. No CRUD yet. Just the contract between the client and our backend.


# Step 1

# Almost every beginner asks: "We already have a SQLAlchemy model. Why do we need Pydantic schemas?"

# Think of a Restaurant
# Imagine you're in a restaurant: Customer -> menu -> Waiter -> Kitchen
# The customer never walks into the kitchen.

# Instead:
# The Menu defines what the customer can order. The Kitchen stores ingredients and cooks food.
# Now map that to our project Client: -> Schema (Menu) -> FastAPI (Waiter) -> Model (Kitchen) -> Database (Ingredients)


# SQLAlchemy Model
# The model represents: How data is stored in PostgreSQL.

# Example:
# The database cares about: id, original_url, short_code, clicks, created_at, Schema.
# The schema represents: What the client sends and receives.

# The client should never send:
from xxlimited import new


{
    "id": 1,
    "clicks": 999,
    "created_at": "..."
}
# Imagine someone sends:
{
    "clicks": 1000000
}
# Should we trust them No. The server decides click count. Not the user.

# This is why Models ≠ Schemas
# Our database model: id, original_url, short_code, clicks, created_at

# Our request schema: original_url That's it.
# The client only provides the URL. Everything else is generated by our application.

# What happens internally?
# Client
#    │
#    ▼
# {
#    "original_url": "https://google.com"
# }
#       │
#       ▼
# Pydantic Schema
#       │
#       ▼
# Validated Data
#       │
#       ▼
# SQLAlchemy Model
#       │
#       ▼
# Database

# Why is this good?
# Imagine someone sends: {"original_url": 12345}

# Without Pydantic: Your code receives bad data.
# With Pydantic: FastAPI automatically returns: 422 Unprocessable Entity before your code even runs.
# That's one of FastAPI's biggest strengths.

# Today's Schemas
# We'll create three.
# schemas/
    # url.py

# Inside it: URLCreate, URLResponse, URLStats

# Why Three?
# URLCreate: Client → Server
{
    "original_url": "https://google.com"
}

# URLResponse: Server → Client
{
    "id": 1,
    "original_url": "...",
    "short_code": "...",
    "short_url": "..."
}

# URLStats: Server → Client
{
    "original_url": "...",
    "clicks": 52,
    "created_at": "..."
}

# Different endpoint. Different response. Different schema.

# Today's Build Plan

# We'll do this: 
# Understand Schemas
#         ↓
# Create url.py
#         ↓
# Build URLCreate
#         ↓
# Test Validation
#         ↓
# Build URLResponse
#         ↓
# Build URLStats

# Imagine we use our SQLAlchemy model directly as the request body. That means the client could send:
# {
#     "id": 500,
#     "clicks": 999999,
#     "created_at": "2035-01-01",
#     "original_url": "https://google.com"
# }

# The SQLAlchemy model represents the database structure, while the client should only provide the data they're allowed to control. Fields like id, clicks, created_at, and short_code are server-managed. Allowing clients to send them could lead to data manipulation and security issues. Therefore, we use Pydantic schemas to expose only the fields the client is permitted to send or receive.







# Create a new file: app/schemas/url.py

# Write this:
# from pydantic import BaseModel, HttpUrl
# class URLCreate(BaseModel):
#     """
#     Schema for creating a new shortened URL.
#     """
#     original_url: HttpUrl

# Let's Understand It

# Why BaseModel?
# Every Pydantic schema inherits from: BaseModel
# Just like every SQLAlchemy model inherits from: Base

# Think of it like this: 
# SQLAlchemy Model → Base
# Pydantic Schema → BaseModel

# Why HttpUrl instead of str?
# This is one of the coolest FastAPI features.

# Imagine someone sends:
{
    "original_url": "hello"
}
# If we use: str It accepts it. But... Is "hello" a valid URL? No.
# If we use: HttpUrl Pydantic automatically validates it.

# Example:
# https://google.com --> Accepted
# https://github.com/Adyaprana --> Accepted
# google --> Rejected
# abc123 --> Rejected
# hello --> Rejected

# FastAPI automatically returns: 422 Unprocessable Entity without us writing any validation code.


# This is why FastAPI is loved
# With Flask, we'd have to write validation ourselves.
# With FastAPI: Client → Pydantic → Validation → FastAPI → Our Code
# Our endpoint only receives valid data.


# Full Code Of: app/schemas/url.py

# from datetime import datetime
# from pydantic import BaseModel, HttpUrl, ConfigDict

# class URLCreate(BaseModel):
#     """
#     Request schema for creating a shortened URL.
#     """
#     original_url: HttpUrl

# class URLResponse(BaseModel):
#     """
#     Response schema after creating a shortened URL.
#     """
#     id: int
#     original_url: HttpUrl
#     short_code: str
#     short_url: str
#     model_config = ConfigDict(from_attributes=True)

# class URLStats(BaseModel):
#     """
#     Response schema for URL statistics.
#     """
#     original_url: HttpUrl
#     short_code: str
#     clicks: int
#     created_at: datetime
#     model_config = ConfigDict(from_attributes=True)


# Two new things today

# 1. ConfigDict(from_attributes=True)
# This is another SQLAlchemy 2.x improvement.
# Old tutorials use:
# class Config:
    # orm_mode = True

# That's Pydantic v1.
# We're using: Pydantic v2, SQLAlchemy 2.x
# So the modern equivalent is: model_config = ConfigDict(from_attributes=True)

# What does it do -> Imagine later we return a SQLAlchemy object.
# Example: url = ShortenedURL(...)
# Instead of manually writing:
# {
#     "id": url.id,
#     "original_url": url.original_url,
#     ...
# }
# Pydantic can automatically read attributes from the SQLAlchemy model and convert them into the API response.
# Think of it like: SQLAlchemy Model → Pydantic Schema → JSON Response


# 2. Why no id in URLCreate?

# Because: The client doesn't create IDs. The database creates them.
# This is one of the biggest lessons today. Request schemas contain only what the client is allowed to send.



# 🎤 Interview Questions (Day 53)

# Q1. What is the difference between a SQLAlchemy Model and a Pydantic Schema?
# Answer: SQLAlchemy Model → Defines how data is stored in the database.
#         Pydantic Schema → Defines what data the API accepts and returns.

# Q2. Why don't we use SQLAlchemy models directly as request bodies?
# Answer: Because the client should not control database-managed fields like id, clicks, created_at, or short_code. Schemas expose only the fields the client is allowed to send.

# Q3. Why use HttpUrl instead of str?
# Answer: HttpUrl automatically validates that the input is a valid HTTP or HTTPS URL. Invalid URLs are rejected before our endpoint logic runs.

# Q4. What does from_attributes=True do?
# Answer: It allows Pydantic to create response objects directly from SQLAlchemy model instances by reading their attributes.

# Q5. Why have separate request and response schemas?
# Answer: The data the client sends is often different from the data the server returns. Separate schemas make the API safer, clearer, and easier to maintain.